---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kedacom.
--- DateTime: 2021/10/23 13:55
---


local redis = require "resty.redis"
local client = redis.connect('1x.6x.1x.1xx', 6384)

client:auth('xxxxxx')
client:select(0)

local confs = redis.call("HGETALL", 'xxx/xxx');
for index, value in ipairs(confs) do
    print(value)
end